### ISSUE TITLE
Weekly Scrum - 08/04/2021

### ISSUE THREAD

**Issue by abdillahinur** [shoaibkhan17/MiniShopify#28]
What have I done this week?
- Added filter functionality to items so user can filter to search for specific item
- Worked on initial filter shops by name and by tags feature
- Contributed to cart backend functionality
- Updated UML Class Diagram

What will I do next week?
- Work on video presentation due Monday April 12th.

What is holding me back?
- N/A

**Comment by kamaluddinshakiri** [comment]
What did I do this week?
- Worked on the backend, created test cases


What will I do next week?
- Will work on the presentation video

What is holding me back?
- Nothing

**Comment by shoaibkhan17** [comment]
What have I done this week?

- Fixed a ton of rendering issues with redux
- Made a deep copy of redux state instead of a shallow copy
- Updated the grid layouts of shops and products
- Cart button on the toolbar + routing
- My shops button on the toolbar + routing
- Display opened shop name
- Fixed rendering issues with update/add/delete products
- Moved the add shop/product button to the bottom of the screen
- Updated cart functionality to add product from redux
- Update cost and quantity of cart product from redux 
- Default empty shop/product image
- SignIn and CreateAccount pop up notification
- Cart model test cases
- Cart badge number updates 
- Leave cart retains the cart items

What will I do next week?

- Work on the presentation

What is holding me back?
- Nothing

**Comment by meetdigrajkar** [comment]
What I have done this week?
- Add shop products to cart (front-end)
- Update Firestore with cart checked out products (back-end)
- Shop API tests for getShops and createShop
- Update cart products in redux 
- Remove products from cart (front-end)

What will I next week?
- Polish presentation and make video

What is holding me back?
- Nothing

**Comment by TamerIbrahim97** [comment]
What have I done this week?

- Did manual testing
What will I do next week?

- Prepare for the presentation
What is holding me back?
- Nothing
